import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
const browser=await chromium.launch({headless:true,executablePath:'/Users/brutus-mac/Library/Caches/ms-playwright/chromium-1228/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing'});
const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1});
const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('/private/tmp/ironfront-threejs-review',{recursive:true});
await page.goto('http://127.0.0.1:5187/three-preview.html');
await page.locator('.metrics strong').filter({hasText:'FPS'}).waitFor({timeout:120000});
await page.waitForTimeout(500);
await page.screenshot({path:'/private/tmp/ironfront-threejs-review/town.png'});
await page.getByLabel('Winter palette').check();
await page.waitForTimeout(500);
await page.screenshot({path:'/private/tmp/ironfront-threejs-review/snow.png'});
await page.getByLabel('Retained building sprites').check();
await page.getByRole('button',{name:'ground',exact:true}).click();
await page.waitForTimeout(500);
await page.screenshot({path:'/private/tmp/ironfront-threejs-review/sprites.png'});
await page.getByRole('button',{name:'Pixi baseline',exact:true}).click();
await page.locator('.pixi canvas').first().waitFor({timeout:60000});
await page.getByRole('button',{name:'Three.js study',exact:true}).click();
await page.locator('.scene canvas').waitFor();
await page.locator('.metrics strong').filter({hasText:'FPS'}).waitFor();
await page.getByLabel('Retained building sprites').uncheck();
await page.getByLabel('Winter palette').uncheck();
await page.getByRole('button',{name:'continent',exact:true}).click();
await page.waitForTimeout(500);
await page.screenshot({path:'/private/tmp/ironfront-threejs-review/continent.png'});
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'town',exact:true}).click();
await page.waitForTimeout(500);
await page.screenshot({path:'/private/tmp/ironfront-threejs-review/mobile.png',fullPage:true});
if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Horizontal overflow');
await page.getByLabel('World seed').fill('Atlas');
await page.getByRole('button',{name:'Generate',exact:true}).click();
await page.locator('#settlement:not([disabled])').waitFor({timeout:120000});
await page.locator('.metrics strong').filter({hasText:'FPS'}).waitFor();
console.log(JSON.stringify({errors,metrics:await page.locator('.metrics').innerText()}));await browser.close();if(errors.length)process.exitCode=1;
